# Generated by Django 6.0.3 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Логин'),
        ),
    ]
