# Generated by Django 6.0.3 on 2026-03-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_room_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ('-created_at',), 'verbose_name': 'Показание датчика', 'verbose_name_plural': 'Показания датчиков'},
        ),
    ]
