# Generated by Django 6.0.3 on 2026-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_sensordata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='conditioner_enabled',
            field=models.BooleanField(default=False, verbose_name='Кондиционер включен'),
        ),
        migrations.AddField(
            model_name='room',
            name='conditioner_mode',
            field=models.CharField(choices=[('off', 'Выключен'), ('heat', 'Обогрев'), ('cool', 'Охлаждение')], default='off', max_length=10, verbose_name='Режим кондиционера'),
        ),
        migrations.AddField(
            model_name='room',
            name='window_open',
            field=models.BooleanField(default=False, verbose_name='Окна открыты'),
        ),
    ]
