# Generated by Django 6.0.3 on 2026-03-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_room_conditioner_enabled_room_conditioner_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='conditioner_enabled',
        ),
        migrations.RemoveField(
            model_name='room',
            name='conditioner_mode',
        ),
        migrations.CreateModel(
            name='ClimateActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.room')),
            ],
            options={
                'verbose_name': 'Лог климатических действий',
                'verbose_name_plural': 'Логи климатических действий',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Conditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кондиционера')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('error', 'Ошибка'), ('disabled', 'Выключен')], default='active', max_length=20, verbose_name='Статус')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включен')),
                ('mode', models.CharField(choices=[('off', 'Выключен'), ('cool', 'Охлаждение'), ('heat', 'Обогрев'), ('fan', 'Вентиляция')], default='off', max_length=10, verbose_name='Режим')),
                ('target_temperature', models.FloatField(blank=True, null=True, verbose_name='Целевая температура')),
                ('power', models.FloatField(default=1.0, verbose_name='Мощность')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Кондиционер',
                'verbose_name_plural': 'Кондиционеры',
            },
        ),
    ]
