# Generated by Django 6.0.3 on 2026-04-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_room_conditioner_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('pair_number', models.IntegerField(blank=True, null=True, verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Предмет')),
                ('teacher', models.CharField(blank=True, max_length=255, verbose_name='Преподаватель')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Группа')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID записи во внешнем источнике')),
                ('source', models.CharField(default='import', max_length=50, verbose_name='Источник')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='university.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Занятие кабинета',
                'verbose_name_plural': 'Занятия кабинетов',
                'ordering': ('lesson_date', 'start_time'),
                'indexes': [models.Index(fields=['room', 'lesson_date', 'start_time'], name='university__room_id_01e818_idx'), models.Index(fields=['lesson_date', 'is_cancelled'], name='university__lesson__700ef6_idx')],
            },
        ),
    ]
