# Generated by Django 6.0.3 on 2026-04-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_teachernotification'),
        ('university', '0006_roomlesson'),
    ]

    operations = [
    ]
