# Generated by Django 6.0.3 on 2026-04-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_merge_0004_teachernotification_0006_roomlesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climateactionlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'История настройки кабинета', 'verbose_name_plural': 'История настройки кабинетов'},
        ),
        migrations.RenameIndex(
            model_name='teachernotification',
            new_name='university__user_id_ccddb7_idx',
            old_name='university_t_user_id_8fb2ab_idx',
        ),
        migrations.RenameIndex(
            model_name='teachernotification',
            new_name='university__lesson__6af5d4_idx',
            old_name='university_t_lesson__ee08c6_idx',
        ),
        migrations.RenameIndex(
            model_name='teachernotification',
            new_name='university__valid_f_9966c4_idx',
            old_name='university_t_valid_f_6523d7_idx',
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='action',
            field=models.CharField(choices=[('ventilation', 'Проветривание'), ('conditioner_cool', 'Кондиционер: охлаждение'), ('conditioner_heat', 'Кондиционер: обогрев'), ('none', 'Без вмешательства')], max_length=50, verbose_name='Выполненное действие'),
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='lesson_date',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='lesson_time',
            field=models.TimeField(verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина выбора действия'),
        ),
        migrations.AlterField(
            model_name='climateactionlog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_logs', to='university.room', verbose_name='Кабинет'),
        ),
    ]
